// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6SAucH3nj58RPOl-x3zGarLzmn-AXAY',
    appId: '1:360513289352:web:874e1b66db148bae32733d',
    messagingSenderId: '360513289352',
    projectId: 'splitsmart-26733',
    authDomain: 'splitsmart-26733.firebaseapp.com',
    storageBucket: 'splitsmart-26733.firebasestorage.app',
    measurementId: 'G-KN0QKW6EB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE0wiqV50A5EMV9ptWujf-jm8JVHczIpk',
    appId: '1:360513289352:android:b5b628bdd42440dc32733d',
    messagingSenderId: '360513289352',
    projectId: 'splitsmart-26733',
    storageBucket: 'splitsmart-26733.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWDlQdMvaAvexSfvXQlNNG28M3KjiRvYs',
    appId: '1:360513289352:ios:20ff2623e8d4747f32733d',
    messagingSenderId: '360513289352',
    projectId: 'splitsmart-26733',
    storageBucket: 'splitsmart-26733.firebasestorage.app',
    iosBundleId: 'com.example.splitsmartApp',
  );
}
